### ISSUE TITLE
When a test is run a second time, it fails

### ISSUE THREAD

**Issue by boris-petrov** [jnormington/dotdiff#18]
The gem works fine with JRuby, thanks! :)

The first time a test is run, an image is generated (btw, it might be a good idea to document this as I was confused in the beginning as to how to generate the screenshots to compare against). The second time it is run, the following error appears:

```
expected Capybara::Session to match image but failed with: 0compare: unable to open image `.../failures/some-image.diff.png': No such file or directory @ error/blob.c/OpenBlob/2701.
```

I can see that in that directory a `.new.png` file is generated, but no `.diff.png` and hence the exception. The funny thing is that when a test is run for the third+ time, everything works fine - a `.diff.png` file is generated and the test passes.

Not sure if this is a problem only on JRuby.

**Comment by jnormington** [comment]
Hey @boris-petrov,

Thanks for the feedback

Yes your correct, and will update the README, by default if the image file doesn't exist it will create it the first time, then on subsequent runs use that base file for comparison.

Also I think I found the issue as well what you experienced, basically we don't use the .diff file we leave it to compare to generate the file. However what I think happened was that the directory didn't exist the first time you ran it. (Reason it worked the third time, because first time would be no comparing, so second time was the first time it was doing comparison with a base file)

You can see from this compare method below that we create the failure image path directory, **BUT** only after we have shelled out the command to compare. Therefore the diff.png file will fail the first time it comes across a image diff and the directory doesn't exist for the compare program to dump its diff out.

https://github.com/jnormington/dotdiff/blob/a4726a475461a91aff9c5a49e8b7c68e51b5e4f0/lib/dotdiff/comparer.rb#L46-L56

I've always had my failure paths already existing for our test suite reason I've never experienced it :facepalm. 

This would be a fairly quick fix to move it earlier on to ensure its present in all cases.

**Comment by boris-petrov** [comment]
I'll be glad to test any fix you come up with. :)

**Comment by jnormington** [comment]
Yeah I'll put a fix in soon.

**Comment by boris-petrov** [comment]
@jnormington - I think this has been fixed, I no longer observe that behavior, right? This issue could be closed if so.
